type  EventCode = "SIGNINDAILY"
  | "ORDERLINE_REQUEST_CREATED"
  | "ORDERLINE_REQUEST_PROCESSED"
  | "ORDER_INVOICE_REQUEST_CREATED"
  | "ORDER_INVOICE_REQUEST_PROCESSED"
  | "ORDER_UPDATED"
  | "GROUP_UPDATED"
  | "GROUP_DELETED"
  | "GROUP_REMOVED"
  | "GROUP_INVITATION_CREATED"
  | "NOTI_TOKEN_REGISTERED"
  | "b";
export default EventCode;
